name: Deployment

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    environment: production
    steps:
      - run: npm -v
      - run: node -v
